# Generated by Django 5.1.2 on 2024-11-02 12:37

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_followers_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
