# Generated by Django 5.1.2 on 2024-11-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_post_link_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
