# Generated by Django 5.1.2 on 2024-11-02 15:27

import socialmedia.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_remove_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=socialmedia.settings.PostImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', storage=socialmedia.settings.ProfilePictureStorage(), upload_to=''),
        ),
    ]
